stages:
  - test
  - deploy

test-default-docker:
  tags:
    - linux
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/erlang:latest
  stage: test
  script:
    - rebar3 compile
    - rebar3 edoc
    - rebar3 dialyzer
    - rebar3 ct
  artifacts:
    when: always
    paths:
      - "_build/test/logs/**"
    expire_in: 3 days
    reports:
      junit:
        - _build/test/logs/last/junit_report.xml

# Pages: publishing Common Test results
pages:
  stage: deploy
  needs:
    - test-default-docker
  script:
    - mv _build/test/logs ./public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH