---
name: Erlang CI
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Erlang/OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['21.3.8.9', '22.3.4.9', '23.3.4.9', '24.3.2', '25.0']
        rebar3: ['3.17']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - name: Compile
        run: rebar3 compile
      - name: Run tests
        run: rebar3 do edoc,ct
