---
name: Erlang CI
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  linux:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp_version: ['21.3.8.9', '22.3.4.9', '23.3.4.9', '24.3.2', '25.0', '26.1.2']
        os: [ubuntu-latest]

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: rebar3 compile
      - name: CT tests
        run: rebar3 do edoc,ct
      - shell: bash
        name: Dialyzer
        run: rebar3 dialyzer
